apiVersion: v1
kind: PersistentVolume
metadata:
  name: dojo-staging-pv
  labels:
    app: dojo
    env: staging
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - nandstorm
  hostPath:
    path: /persist/dojo/staging
    type: DirectoryOrCreate
