 # Keel Helm chart via Rancher's HelmChart CRD. Chart releases: https://github.com/keel-hq/keel-helm-chart
apiVersion: v1
kind: Namespace
metadata:
  name: keel
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: keel
  namespace: kube-system
spec:
  repo: https://charts.keel.sh
  chart: keel
  version: 1.0.5
  targetNamespace: keel
  valuesContent: |-
    helmProvider:
      enabled: false
