resources:
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.27.1/controller.yaml
  - cloudflare-cert-manager.sealed.yaml
  - cloudflare-external-dns.sealed.yaml
  - cert-manager.yaml
  - external-dns.yaml
  - metallb
  - nvidia
  - traefik.yaml
  - keel.yaml
