apiVersion: apps/v1
kind: Deployment
metadata:
  name: dojo
  annotations:
    keel.sh/policy: "force"
    keel.sh/trigger: "poll"
    keel.sh/match-tag: "true"
    keel.sh/pollSchedule: "@every 60s"
