apiVersion: apps/v1
kind: Deployment
metadata:
  name: dojo
spec:
  template:
    spec:
      containers:
        - name: dojo
          imagePullPolicy: Always
      initContainers:
        - name: fix-permissions
          image: ghcr.io/blogle/dojo:staging
          imagePullPolicy: Always
          command: ["/bin/sh", "-c", "chown -R 1000:1000 /data"]
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: data
            mountPath: /data
